# Generated by Django 4.2 on 2025-06-13 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mytodo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='complate',
            field=models.IntegerField(default=0, verbose_name='完了フラグ'),
        ),
        migrations.AlterField(
            model_name='task',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='終了日'),
        ),
        migrations.AlterField(
            model_name='task',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='開始日'),
        ),
    ]
