# Generated by Django 4.2 on 2025-06-16 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mytodo', '0002_alter_task_complate_alter_task_end_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='complate',
        ),
        migrations.AddField(
            model_name='task',
            name='complete',
            field=models.IntegerField(default=0, verbose_name='完了フラグ'),
        ),
    ]
